name: flutter_subtitle
description: show subtitle anywhere (chewie, videoplayer, etc.), suporrt webvtt and srt.
version: 0.0.6
homepage: https://github.com/shiyiya/flutter_subtitle

environment:
  sdk: '>=2.16.2 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
